<?php

namespace Netvlies\Bundle\PublishBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandLog repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandLogRepository extends EntityRepository
{

    /**
     * @param Target $target
     * @return mixed
     */
    public function getLogsByTargets($targets, $limit=null){

        $entityManager = $this->getEntityManager();

        $ids = array();
        foreach($targets as $target){
            $ids[] = $target->getId();
        }

        $query = $entityManager->createQuery('
            SELECT c FROM Netvlies\Bundle\PublishBundle\Entity\CommandLog c
            WHERE c.target IN (:ids)
            ORDER BY c.id DESC
        ')->setParameter('ids', $ids);


        if(!is_null($limit)){
            $query->setMaxResults($limit);
        }

        return $query->getResult();
    }


}
