<?php
/**
 * This file is part of Organist
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author: markri <mdekrijger@netvlies.nl>
 */

namespace Netvlies\Bundle\PublishBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandLog repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandLogRepository extends EntityRepository
{

    /**
     * @param Target $target
     * @return mixed
     */
    public function getLogsForApplication($application, $limit=null)
    {
        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery('
            SELECT c FROM Netvlies\Bundle\PublishBundle\Entity\CommandLog c
            WHERE c.application = :app
            ORDER BY c.id DESC
        ')->setParameter('app', $application);


        if(!is_null($limit)){
            $query->setMaxResults($limit);
        }

        return $query->getResult();
    }
}