<?php

namespace Netvlies\Bundle\PublishBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConsoleLog repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsoleLogRepository extends EntityRepository
{

    /**
     * @param Target $target
     * @return mixed
     */
    public function getLogsByTargets($targets){

        $entityManager = $this->getEntityManager();

        $ids = array();
        foreach($targets as $target){
            $ids[] = $target->getId();
        }

        $query = $entityManager->createQuery('
            SELECT c FROM Netvlies\Bundle\PublishBundle\Entity\ConsoleLog c
            WHERE c.targetId IN (:ids)
            ORDER BY c.id DESC
        ')->setParameter('ids', $ids);


        return $query->getResult();
    }


}
