<?php

namespace Netvlies\PublishBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnvironmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvironmentRepository extends EntityRepository
{

    public function getByTypeAndHost($type, $host){

        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery('
            SELECT e FROM Netvlies\PublishBundle\Entity\Environment e
            WHERE e.type = :type
            AND e.hostname = :host
        ');

        $query->setParameter('type', $type);
        $query->setParameter('host', $host);

        return $query->getResult();
    }


}