<?php

namespace Netvlies\PublishBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
    
    /**
     * Get all sites
     */
    public function getAllSites(){
        return $this->findBy(array(), array('name' => 'ASC'));
        
        //return $this->findBy(array('1=1'), array('name'));
    }
}