<?php

namespace Netvlies\PublishBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TargetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TargetRepository extends EntityRepository
{

    public function getByAppAndEnv($application, $environment){

        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery('
            SELECT d FROM Netvlies\PublishBundle\Entity\Deployment d
            WHERE d.application = :app
            AND d.environment = :env
        ');

        $query->setParameter('app', $application);
        $query->setParameter('env', $environment);

        return $query->getResult();
    }


}