language: php
php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - cp app/config/parameters.T.yml app/config/parameters.yml
    - composer install --dev

script:  phpunit --configuration app/phpunit.xml.dist