branches:
    only:
        - master

language: php
php:
    - 5.5
    - 5.6

before_script:
    - cp app/config/parameters.T.yml app/config/parameters.yml
    - git config --global user.email "mdekrijger@netvlies.nl"
    - git config --global user.name "M. de Krijger"
    - composer install --dev
    - app/console cache:clear --env=test

script:  phpunit --configuration app/phpunit.xml.dist
