phpcli:
  build: docker/php-cli-5.6
  volumes:
      - .:/var/www/html/organist
      - ./docker/php-fpm-5.6/php.ini:/usr/local/etc/php/php.ini
  tty: true
  links:
    - mysql:mysql

phpfpm:
  build: docker/php-fpm-5.6
  volumes:
    - ./docker/php-fpm-5.6/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./docker/php-fpm-5.6/php.ini:/usr/local/etc/php/php.ini
    - ./docker/log/php-fpm:/var/log/php-fpm
  volumes_from:
   - phpcli
  ports:
    - 9000:9000
  links:
    - mysql:mysql

nginx:
  image: nginx
  ports:
    - "80:80"
  links:
    - phpfpm:phpfpm
    - node:node
  volumes:
    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./docker/log/nginx:/var/log/nginx
  volumes_from:
   - phpcli


mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: organist
    MYSQL_USER: organist
    MYSQL_PASSWORD: organist
    MYSQL_DATABASE: organist
  volumes:
    - ./docker/mysql/databases:/var/lib/mysql
    - ./docker/log/mysql:/var/log/mysql

node:
   build: docker/node
   volumes_from:
   - phpcli
   ports:
     - 8080:8080
   links:
    - mysql:mysql
