application:
    build: docker/application
    volumes:
        - .:/var/www/organist
        #- logs/symfony:/var/www/symfony/app/logs
    #tty: true

phpfpm:
  build: docker/php-fpm-5.6
  restart: always
  volumes:
    - ./docker/php-fpm-5.6/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./docker/php-fpm-5.6/php.ini:/usr/local/etc/php/php.ini
    - ./docker/log/php-fpm:/var/log/php-fpm
  volumes_from:
   - application
  ports:
    - 9000:9000
  links:
    - db:db

nginx:
  image: nginx
  restart: always
  ports:
    - "80:80"
  links:
    - phpfpm:phpfpm
  volumes:
    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./docker/log/nginx:/var/log/nginx
  volumes_from:
   - application

db:
  image: mysql
  restart: always
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: organist
    MYSQL_USER: organist
    MYSQL_PASSWORD: organist
    MYSQL_DATABASE: organist
  volumes:
    - ./docker/mysql/databases:/var/lib/mysql
    - ./docker/log/mysql:/var/log/mysql
