phpcli:
  build: docker/php-cli-5.6
  restart: always
  ports:
    - "8080:8080"
  volumes:
    - .:/var/www/html/organist
    - ./docker/php-fpm-5.6/php.ini:/usr/local/etc/php/php.ini
  tty: true
  environment:
    npm_package_config_port: 8080
    npm_package_config_dbhost: mysql
    npm_package_config_dbname: live
    npm_package_config_dbuser: root
    npm_package_config_dbpassword: organist
    npm_package_config_table: CommandLog
    npm_package_config_idField: id
    npm_package_config_commandField: command
    npm_package_config_logField: log
  links:
    - mysql:mysql

phpfpm:
  build: docker/php-fpm-5.6
  restart: always
  volumes:
    - ./docker/php-fpm-5.6/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./docker/php-fpm-5.6/php.ini:/usr/local/etc/php/php.ini
    - ./docker/log/php-fpm:/var/log/php-fpm
  volumes_from:
   - phpcli
  ports:
    - 9000:9000
  links:
    - mysql:mysql

nginx:
  image: nginx
  restart: always
  ports:
    - "80:80"
  links:
    - phpfpm:phpfpm
    - phpcli:phpcli
  volumes:
    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./docker/log/nginx:/var/log/nginx
  volumes_from:
   - phpcli


mysql:
  image: mysql
  restart: always
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: organist
    MYSQL_USER: organist
    MYSQL_PASSWORD: organist
    MYSQL_DATABASE: organist
  volumes:
    - ./docker/mysql/databases:/var/lib/mysql
    - ./docker/log/mysql:/var/log/mysql
