parameters:
#    netvlies_publish.example.class: Netvlies\PublishBundle\Example

services:
#    netvlies_publish.example:
#        class: %netvlies_publish.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
