services:
    # services
    bitbucket:
        class:   Netvlies\PublishBundle\Services\Scm\GitBitbucket
        arguments: [@service_container]

    console_controller:
        class:    Netvlies\PublishBundle\Controller\ConsoleController
        calls:
            - [ setContainer, [ @service_container ] ]

    scriptbuilder:
        class:  Netvlies\PublishBundle\Services\ScriptBuilder


    # form types
    netvlies.publish.form.environment_selector:
        class: Netvlies\PublishBundle\Form\EnvironmentType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: environment_selector }

    netvlies.publish.form.target_selector:
        class: Netvlies\PublishBundle\Form\TargetType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: target_selector }