imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            true
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                connection: default
                mappings:
                    OrganistBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


organist:
    repositorypath: "%repository_path%"
    anyterm_user: deploy   # this local user is used for connecting to remote hosts for deployment and git user
    anyterm_exec_port: 7778 # anyterm port
    strategies:
        capistrano2:
            label: Capistrano 2
        capistrano3:
            label: Capistrano 3
    externalstatus:
        bitbucket: true
        github: false
    applicationtypes:
        symfony:
            label: Symfony
        wordpress:
            label: Wordpress
            userdirs: [ 'wp-content/uploads' ]
        oms:
            label: My Fancy CMS
            userdirs: [ 'media', 'cache', 'lucene', 'tmp' ]
            userfiles: [ 'cms/.htpasswd', 'cms/.htaccess' ]
        drupal:
            label: Drupal
            userdirs: [ 'sites/default/files' ]
