imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:
        save_path: /tmp #temporary thing to have it working in dev env

# Twig Configuration
twig:
    debug:            true
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                connection: default
                mappings:
                    NetvliesPublishBundle: ~
                #auto_generate_proxy_classes: %kernel.debug%
                #auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


netvlies_publish:
    repositorypath: %repository_path%
    console_port: 7779
    strategies:
        capistrano2:
            label: Capistrano 2
            rvm: ruby-1.8.7-head
            commands:
                deploy:
                    default: true
                    label: Deploy
                    template: Netvlies\Bundle\PublishBundle\Strategy\Commands\Capistrano2\deploy.txt.twig
                    parameters:
                        target:
                            type: target_choicelist
                            options:
                                label: Target
                                required: true
                        reference:
                            type: reference_choicelist
                            options:
                                label: Reference
                                required: true
                rollback:
                    default: true
                    label: Rollback
                    template: Netvlies\Bundle\PublishBundle\Strategy\Commands\Capistrano2\rollback.txt.twig
                    parameters:
                        target:
                            type: target_choicelist
                            options:
                                label: Target
                                required: true
                setup:
                    default: true
                    label: Setup
                    template: Netvlies\Bundle\PublishBundle\Strategy\Commands\Capistrano2\init.txt.twig
                    parameters:
                        target:
                            type: target_choicelist
                            options:
                                label: Target
                                required: true
#        capistrano3:
#            label: Capistrano 3
#            rvm: ruby-2.2.3
#            commands:
##                deploy:
##                rollback:
##                setup:
#        phing:
#            label: Phing
#            commands:
#                # commands depend on content of build.xml, therefore build.xml tasks should be parsed
    externalstatus:
        bitbucket: true
        github: false
#    versioningservices:
#        git:
#            forward_key: /home/deploy/.ssh/id_rsa_bitbucket
    applicationtypes:
        symfony20:
            label: Symfony 2.0
        symfony23:
            label: Symfony 2.3
        symfony27:
            label: Symfony 2.7
        wordpress:
            label: Wordpress
            userdirs: [ 'wp-content/uploads' ]
        oms:
            label: My Fancy CMS
            userdirs: [ 'media', 'cache', 'lucene', 'tmp' ]
            userfiles: [ 'cms/.htpasswd', 'cms/.htaccess' ]
        drupal:
            label: Drupal
            userdirs: [ 'sites/default/files' ]
