imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true


opensky_ldap:
    client:
        host: fs1
        port: 389
        allowEmptyPassword: true
        # see http://framework.zend.com/manual/en/zend.ldap.api.html for options
    user_base_dn:        ou=Gebruikers,dc=netvlies,dc=breda
    user_filter:         (objectClass=*)
    username_attribute:  uid
    role_base_dn:        ou=Groepen,dc=netvlies,dc=breda
    role_filter:         (objectClass=Personeel)
    role_name_attribute: cn
    role_user_attribute: memberuid
    security:
        role_prefix:   ROLE_LDAP_
        default_roles: [ROLE_ADMIN, ROLE_LDAP]

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

#@todo needs to be removed
services:
    console:
        class:   Netvlies\PublishBundle\Console


parameters:
    repositorypath: /var/www/vhosts/publish/web/repos
    privkeyfile: /var/www/.ssh/id_dsa
    pubkeyfile: /var/www/.ssh/id_dsa.pub
imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true


opensky_ldap:
    client:
        host: fs1
        port: 389
        username: markri
        optReferrals:
        allowEmptyPassword: true
    user_base_dn:        ou=Gebruikers,dc=netvlies,dc=breda
    user_filter:         (objectClass=*)
    username_attribute:  uid
    role_base_dn:        ou=Groepen,dc=netvlies,dc=breda
    role_filter:         (objectClass=Personeel)
    role_name_attribute: cn
    role_user_attribute: memberuid
    security:
        role_prefix:   ROLE_LDAP_
        default_roles: [ROLE_ADMIN, ROLE_LDAP]

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

#@todo needs to be removed
services:
    console:
        class:   Netvlies\PublishBundle\Console


parameters:
    repositorypath: /var/www/vhosts/publish/web/repos
    privkeyfile: /var/www/.ssh/id_dsa
    pubkeyfile: /var/www/.ssh/id_dsa.pub
imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true


opensky_ldap:
    client:
        host: fs1
        port: 389
        username: markri
        optReferrals:
        allowEmptyPassword: true
    user_base_dn:        ou=Gebruikers,dc=netvlies,dc=breda
    user_filter:         (objectClass=*)
    username_attribute:  uid
    role_base_dn:        ou=Groepen,dc=netvlies,dc=breda
    role_filter:         (objectClass=Personeel)
    role_name_attribute: cn
    role_user_attribute: memberuid
    security:
        role_prefix:   ROLE_LDAP_
        default_roles: [ROLE_ADMIN, ROLE_LDAP]

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

#@todo needs to be removed
services:
    console:
        class:   Netvlies\PublishBundle\Console


parameters:
    repositorypath: /var/www/vhosts/publish/web/repos
    privkeyfile: /var/www/.ssh/id_dsa
    pubkeyfile: /var/www/.ssh/id_dsa.pub
imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true


opensky_ldap:
    client:
        host: fs1
        port: 389
        username: markri
        optReferrals:
        allowEmptyPassword: true
    user_base_dn:        ou=Gebruikers,dc=netvlies,dc=breda
    user_filter:         (objectClass=*)
    username_attribute:  uid
    role_base_dn:        ou=Groepen,dc=netvlies,dc=breda
    role_filter:         (objectClass=Personeel)
    role_name_attribute: cn
    role_user_attribute: memberuid
    security:
        role_prefix:   ROLE_LDAP_
        default_roles: [ROLE_ADMIN, ROLE_LDAP]

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

#@todo needs to be removed
services:
    console:
        class:   Netvlies\PublishBundle\Console


parameters:
    repositorypath: /var/www/vhosts/publish/web/repos
    sudouser: deploy
    privkeyfile: /var/lib/jenkins/.ssh/id_dsa
    pubkeyfile: /var/lib/jenkins/.ssh/id_dsa.pub
