parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     organist
    database_user:     root
    database_password: vagrant

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    repository_path:  /home/deploy/organist/web/repos

    #@todo refactor this in config.yml in versioning services as option
    versioning_private_key:   /home/deploy/.ssh/id_rsa_bitbucket

