parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     organist
    database_user:     root
    database_password: vagrant

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    repository_path:   /home/deploy/organist/app/web/repos

    repository_path:  /home/deploy/organist/app/web/repos

