parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     organist
    database_user:     root
    database_password: vagrant

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    repository_path:  /home/deploy/organist/web/repos
    private_key: /home/organist/.ssh/private_key

    dev_oauth_id: id
    dev_oauth_secret: secret

    prod_oauth_id: id
    prod_oauth_secret: secret

    # Change this to IS_AUTHENTICATED_FULLY when you want to use the oauth provider. Or to IS_AUTHENTICATED_ANONYMOUSLY for disabling login
    minimum_security_role: IS_AUTHENTICATED_ANONYMOUSLY

    # Optional check when using oauth to restrict e-mail adresses from certain domain
    oauth_mail_regex: /@netvlies.net$/i

    jenkins_user:
    jenkins_password: