# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

OrganistBundle:
    resource: "@OrganistBundle/Controller/"
    type:     annotation
    prefix:   /

google_login:
    pattern: /login/check-google