security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        oauth:
            id: netvlies_publish.userprovider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: true
            pattern: ^/
            oauth:
                resource_owners:
                    google:        /login/check-google
                login_path:        /connect/google
                failure_path:      /connect-fail
                oauth_user_provider:
                    service: netvlies_publish.userprovider

    access_control:
        - { path: ^/connect-fail, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/google, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/check-google, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: %minimum_security_role% }
