services:

    organist.versioning.git:
        class: Markri\Bundle\OrganistBundle\Versioning\Git\Git
        arguments: [ "%organist.repositorypath%", '/home/deploy/.ssh/id_rsa_bitbucket' ]
        tags:
          - { name: organist.versioning, alias: Git }

