services:

    netvlies_publish.versioning.git:
        class: Netvlies\Bundle\PublishBundle\Versioning\Git\Git
        arguments: [ %netvlies_publish.repositorypath%, '/home/deploy/.ssh/id_rsa_bitbucket' ]
        tags:
          - { name: netvlies_publish.versioning, alias: Git }

