FROM nginx:1.10.1
# Note that we want to compile mod security into nginx
# and run latest stable nginx on CentOS. Instead of default EPEL nginx 1.6
#RUN rm /etc/nginx/nginx.conf && \
#    rm /etc/nginx/conf.d/default.conf
#    mkdir -p /var/www/html

EXPOSE 80 443