services:

    # form types
    netvlies.publish.form.environment_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\EnvironmentType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: environment_choicelist }

    netvlies_publish.form.target_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\TargetChoiceList
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: target_choicelist }

    netvlies_publish.form.reference_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\ReferenceChoiceList
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: reference_choicelist }

    netvlies_publish.form.branch_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\BranchChoiceList
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: branch_choicelist }

    netvlies_publish.form.versioning_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\VersioningChoiceList
        arguments: [ %netvlies_publish.versioningKeyLabels% ]
        tags:
            - {name: form.type, alias: versioning_choicelist }

    netvlies_publish.form.strategy_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\StrategyType
        arguments: [ %netvlies_publish.strategyKeyLabels% ]
        tags:
            - {name: form.type, alias: strategy_choicelist }

    netvlies_publish.form.applicationtype_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\ApplicationTypeChoiceList
        arguments: [ %netvlies_publish.applicationTypeKeyLabels% ]
        tags:
            - {name: form.type, alias: applicationtype_choicelist }

    netvlies_publish.form.onetomany:
        class: Netvlies\Bundle\PublishBundle\Form\OneToManyType
        tags:
            - { name: form.type, alias: onetomany }

    netvlies_publish_twig_extensions:
        class: Netvlies\Bundle\PublishBundle\Twig\Extensions\PublishExtensions
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: twig.extension }


    netvlies_publish.userprovider:
        class: Netvlies\Bundle\PublishBundle\Security\UserProvider
        arguments: [ %oauth_mail_regex% ]
