services:

    git:
        class: Netvlies\Bundle\PublishBundle\Services\Scm\Git
        arguments: [ @netvlies_publish.applicationHelper ]

    netvlies_publish.applicationHelper:
        class: Netvlies\Bundle\PublishBundle\Services\ApplicationHelper
        arguments: [ %repository_path% ]


    console_controller:
        class:    Netvlies\Bundle\PublishBundle\Controller\ConsoleController
        calls:
            - [ setContainer, [ @service_container ] ]

    scriptbuilder:
        class:  Netvlies\Bundle\PublishBundle\Services\ScriptBuilder


    # form types
    netvlies.publish.form.environment_selector:
        class: Netvlies\Bundle\PublishBundle\Form\EnvironmentType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: environment_selector }

    netvlies_publish.form.target_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\TargetChoiceList
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: target_choicelist }

    netvlies_publish.form.reference_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\ReferenceChoiceList
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: reference_choicelist }


    netvlies_publish.form.scm_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\ScmChoiceList
        arguments: [ %netvlies_publish.scmtypes% ]
        tags:
            - {name: form.type, alias: scm_choicelist }


    # dashboard application selector
    netvlies_publish_twig_applicationselect:
        class: Netvlies\Bundle\PublishBundle\Twig\Extensions\ApplicationSelect
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: twig.extension }

