services:

    git:
        class: Netvlies\Bundle\PublishBundle\Versioning\Git\Git
        arguments: [ %repository_path%, %versioning_private_key% ]

    console_controller:
        class:    Netvlies\Bundle\PublishBundle\Controller\ConsoleController
        calls:
            - [ setContainer, [ @service_container ] ]

    # form types
    netvlies.publish.form.environment_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\EnvironmentType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: environment_choicelist }

    netvlies_publish.form.target_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\TargetChoiceList
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: target_choicelist }

    netvlies_publish.form.reference_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\ReferenceChoiceList
        arguments: [ @service_container ]
        tags:
            - { name: form.type, alias: reference_choicelist }


    netvlies_publish.form.versioning_selector:
        class: Netvlies\Bundle\PublishBundle\Form\ChoiceList\VersioningChoiceList
        arguments: [ %netvlies_publish.versioningtypes% ]
        tags:
            - {name: form.type, alias: versioning_choicelist }


    # dashboard application selector
    netvlies_publish_twig_applicationselect:
        class: Netvlies\Bundle\PublishBundle\Twig\Extensions\ApplicationSelect
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: twig.extension }

