services:

    git:
        class: Netvlies\Bundle\PublishBundle\Services\Git
        arguments: [ @netvlies_publish.applicationHelper ]

    netvlies_publish.applicationHelper:
        class: Netvlies\Bundle\PublishBundle\Services\ApplicationHelper
        arguments: [ %repository_path% ]






    console_controller:
        class:    Netvlies\Bundle\PublishBundle\Controller\ConsoleController
        calls:
            - [ setContainer, [ @service_container ] ]

    scriptbuilder:
        class:  Netvlies\Bundle\PublishBundle\Services\ScriptBuilder


    # form types
    netvlies.publish.form.environment_selector:
        class: Netvlies\Bundle\PublishBundle\Form\EnvironmentType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: environment_selector }

    netvlies.publish.form.target_selector:
        class: Netvlies\Bundle\PublishBundle\Form\TargetType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: target_selector }


    netvlies_publish_twig_applicationselect:
        class: Netvlies\Bundle\PublishBundle\Twig\Extensions\ApplicationSelect
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: twig.extension }


#    # todo remove this i guess
#    gitbitbucket:
#        class:   Netvlies\Bundle\PublishBundle\Services\Scm\GitBitbucket
#        calls:
#            - [ setContainer, [ @service_container ] ]
