<?php

namespace Netvlies\Bundle\PublishBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParameterSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterSetRepository extends EntityRepository
{
}