#!/bin/bash
#
# description: Anytermd server
# processname: anyterm
# chkconfig: 51 51 51
#
# Get function from functions library

# Start the service anyterm
start() {
        echo "Starting anyterm daemon"
        #path# organist:anyterm start

}

# Stop the service Anyterm
stop() {
        echo "Stopping Anyterm server"
        #path# organist:anyterm stop
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        #path# organist:anyterm restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0